### ISSUE TITLE
Enable/disable motion, face detection using mqtt

### ISSUE THREAD

**Issue by DrPerryCoke** [thecowan/wallpanel-android#321]
Good day!
I would like to be able to enable / disable motion, face detection using mqtt

**Comment by thanksmister** [comment]
Don’t we already have a command to turn off the camera?  They are connected, so both would be disabled.

**Comment by DrPerryCoke** [comment]
> Don’t we already have a command to turn off the camera? They are connected, so both would be disabled.

I know that there is) But I wanted the camera and the motion sensor to always work, and I turned on face recognition only when necessary. If this is a problem, please excuse me.
