### ISSUE TITLE
Wiki documentation missing

### ISSUE THREAD

**Issue by wizmo2** [thecowan/wallpanel-android#327]
Github Wiki links need updating to the new @thecowan pages.  @thanksmister pages are archives and inaccessible

**Comment by joshualyon** [comment]
In the meantime, you can use the side-bar to navigate between the wiki pages.

**Comment by etxttul** [comment]
Hi,

I just can't find the wiki, if it is there please add a link.

Thanks
Tobe

**Comment by etxttul** [comment]
I might be blond, but when I click on the wiki, I find what I'm looking for [MQTT and HTTP Commands](https://github.com/thanksmister/wallpanel-android/wiki/MQTT-and-HTTP-Commands).
But when I click on that I get to https://github.com/thanksmister/wallpanel-android.
So I click on the Wiki again and again I find [MQTT and HTTP Commands](https://github.com/thanksmister/wallpanel-android/wiki/MQTT-and-HTTP-Commands), but when I click on that I just get back to https://github.com/thanksmister/wallpanel-android. Some links seems to be broken here.

**Comment by wizmo2** [comment]
At least on the Desktop version of the Wiki page, the index table to the right does work.

@thecowan the links on the Home page of the Wiki needs editing.

**Comment by thanksmister** [comment]
Please read this issue, https://github.com/thecowan/wallpanel-android/issues/341.  This project was abandoned by @thecowan and it now has a new maintainer and repository.  In the meantime, I have fixed the wiki links to point to the correct pages.  Please use the new repository to post any issues going forward.
