### ISSUE TITLE
[BUG] Version 0.12.0 not waking screen

### ISSUE THREAD

**Issue by LuboZ** [thecowan/wallpanel-android#364]
**Describe the bug**
Hello, i have tablet samsung galaxy a7 lite. Wallpanel stopped waking up the screen after the latest update. It is working only If the screen is dimmed. When the screen shut down, it is impossible to wake it up by motion, but also by mqtt command.

**Smartphone:**
 - Device: Samsung galaxy tab A7 lite
 - Android version 13

**Comment by GernotAlthammer** [comment]
Hello, i have the same problem. Galaxy Tab At does not wake up the screen when sending MQTT command

  #### MQTT Buttons ####
  - button:
      unique_id: taba7_turn_screen_on
      name: "TabA7 Turn Screen ON"
      command_topic: "tablet/taba7/commands"
      payload_press: '{ "wake": true }'

**Comment by LuboZ** [comment]
Nevermind, I just switched to fully kiosk browser, everything works like a charm for 10 euros.
